import { CdkAccordionModule } from '@angular/cdk/accordion';
import { DialogModule } from '@angular/cdk/dialog';
import { DragDropModule } from '@angular/cdk/drag-drop';
import { CdkMenuModule } from '@angular/cdk/menu';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { CdkTableModule } from '@angular/cdk/table';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatMenuModule } from '@angular/material/menu';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatRadioModule } from '@angular/material/radio';
import { MatSelectModule } from '@angular/material/select';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatSortModule } from '@angular/material/sort';
import { MatTableModule } from '@angular/material/table';
import { MatTabsModule } from '@angular/material/tabs';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule } from '@angular/router';
import {
  TuiActiveZoneModule,
  TuiAlertHostModule,
  TuiAutoFocusModule,
  TuiAutofilledModule,
  TuiCheckedModule,
  TuiControlModule,
  TuiCopyProcessorModule,
  TuiDialogHostModule,
  TuiDropdownHostModule,
  TuiDroppableModule,
  TuiElementModule,
  TuiFilterPipeModule,
  TuiFocusTrapModule,
  TuiFocusVisibleModule,
  TuiFocusableModule,
  TuiFocusedModule,
  TuiForModule,
  TuiHighDpiModule,
  TuiHoveredModule,
  TuiIsPresentPipeModule,
  TuiItemModule,
  TuiKeysPipeModule,
  TuiLetModule,
  TuiMapperPipeModule,
  TuiMediaModule,
  TuiObscuredModule,
  TuiOverscrollModule,
  TuiPanModule,
  TuiPortalModule,
  TuiPressedModule,
  TuiRepeatTimesModule,
  TuiReplacePipeModule,
  TuiResizeModule,
  TuiResizerModule,
  TuiSwipeModule,
  TuiValidatorModule,
  TuiValueChangesModule,
  TuiZoomModule,
} from '@taiga-ui/cdk';
import {
  TuiAlertModule,
  TuiButtonModule,
  TuiCalendarModule,
  TuiCalendarSheetPipeModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiDropdownModule,
  TuiErrorModule,
  TuiExpandModule,
  TuiFlagPipeModule,
  TuiFormatDatePipeModule,
  TuiFormatNumberPipeModule,
  TuiFormatPhonePipeModule,
  TuiGroupModule,
  TuiHintModule,
  TuiHintsHostModule,
  TuiHostedDropdownModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiMaskAccessorModule,
  TuiModeModule,
  TuiMonthPipeModule,
  TuiNotificationModule,
  TuiPrimitiveCalendarModule,
  TuiPrimitiveCheckboxModule,
  TuiPrimitiveSpinButtonModule,
  TuiPrimitiveTextfieldModule,
  TuiPrimitiveYearMonthPaginationModule,
  TuiPrimitiveYearPickerModule,
  TuiRootModule,
  TuiScrollIntoViewModule,
  TuiScrollbarModule,
  TuiSvgDefsHostModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
  TuiThemeNightModule,
  TuiTooltipModule,
  TuiWrapperModule,
} from '@taiga-ui/core';
import {
  TuiAccordionModule,
  TuiActionModule,
  TuiArrowModule,
  TuiAvatarModule,
  TuiBadgeModule,
  TuiBadgedContentModule,
  TuiBreadcrumbsModule,
  TuiCalendarMonthModule,
  TuiCalendarRangeModule,
  TuiCarouselModule,
  TuiCheckboxBlockModule,
  TuiCheckboxLabeledModule,
  TuiCheckboxModule,
  TuiComboBoxModule,
  TuiDataListDropdownManagerModule,
  TuiDataListWrapperModule,
  TuiElasticContainerModule,
  TuiExtractCountryCodeModule,
  TuiFieldErrorPipeModule,
  TuiFilesModule,
  TuiFilterByInputPipeModule,
  TuiFilterModule,
  TuiHighlightModule,
  TuiInputCopyModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputDateTimeModule,
  TuiInputFilesModule,
  TuiInputInlineModule,
  TuiInputModule,
  TuiInputMonthModule,
  TuiInputMonthRangeModule,
  TuiInputNumberModule,
  TuiInputPasswordModule,
  TuiInputPhoneInternationalModule,
  TuiInputPhoneModule,
  TuiInputRangeModule,
  TuiInputSliderModule,
  TuiInputTagModule,
  TuiInputTimeModule,
  TuiInputYearModule,
  TuiIslandModule,
  TuiIsoToCountryCodeModule,
  TuiItemsWithMoreModule,
  TuiLazyLoadingModule,
  TuiLineClampModule,
  TuiMarkerIconModule,
  TuiMultiSelectModule,
  TuiMultiSelectOptionModule,
  TuiPaginationModule,
  TuiPdfViewerModule,
  TuiPresentModule,
  TuiPrimitiveCalendarRangeModule,
  TuiProgressModule,
  TuiProjectClassModule,
  TuiPromptModule,
  TuiPushModule,
  TuiRadioBlockModule,
  TuiRadioGroupModule,
  TuiRadioLabeledModule,
  TuiRadioListModule,
  TuiRadioModule,
  TuiRangeModule,
  TuiRatingModule,
  TuiRoutableDialogModule,
  TuiSelectModule,
  TuiSelectOptionModule,
  TuiSliderModule,
  TuiSortCountriesPipeModule,
  TuiStepperModule,
  TuiStringifyContentPipeModule,
  TuiStringifyPipeModule,
  TuiTabsModule,
  TuiTagModule,
  TuiTilesModule,
  TuiToYearPipeModule,
  TuiToggleModule,
  TuiTreeModule,
  TuiUnfinishedValidatorModule,
  TuiValueAccessorModule
} from '@taiga-ui/kit';
import { PolymorpheusModule } from '@tinkoff/ng-polymorpheus';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import { AppRoutingModule } from '../app-routing.module';
import { DFormsModule } from '../core/dynamic-forms/dForms.module';
import { CdkDragdropModule } from '../Examples/cdkDrag&Drop/cdkDrag&drop.module';


export const ALL_MODULES = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  ReactiveFormsModule,
  ScrollingModule,
  PolymorpheusModule,
  RouterModule.forRoot([]),
  TuiActiveZoneModule,
  TuiAlertHostModule,
  TuiAutoFocusModule,
  TuiAutofilledModule,
  TuiCheckedModule,
  TuiControlModule,
  TuiCopyProcessorModule,
  TuiDialogHostModule,
  TuiDropdownHostModule,
  TuiDroppableModule,
  TuiElementModule,
  TuiFilterPipeModule,
  TuiFocusTrapModule,
  TuiFocusVisibleModule,
  TuiFocusableModule,
  TuiFocusedModule,
  TuiForModule,
  TuiHighDpiModule,
  TuiHoveredModule,
  TuiIsPresentPipeModule,
  TuiItemModule,
  TuiKeysPipeModule,
  TuiLetModule,
  TuiMapperPipeModule,
  TuiMediaModule,
  TuiObscuredModule,
  TuiOverscrollModule,
  TuiPanModule,
  TuiPortalModule,
  TuiPressedModule,
  TuiRepeatTimesModule,
  TuiReplacePipeModule,
  TuiResizeModule,
  TuiResizerModule,
  TuiSwipeModule,
  TuiValidatorModule,
  TuiValueChangesModule,
  TuiZoomModule,
  TuiAlertModule,
  TuiButtonModule,
  TuiCalendarModule,
  TuiCalendarSheetPipeModule,
  TuiDataListModule,
  TuiDialogModule,
  TuiDropdownModule,
  TuiErrorModule,
  TuiExpandModule,
  TuiFlagPipeModule,
  TuiFormatDatePipeModule,
  TuiFormatNumberPipeModule,
  TuiFormatPhonePipeModule,
  TuiGroupModule,
  TuiHintModule,
  TuiHintsHostModule,
  TuiHostedDropdownModule,
  TuiLabelModule,
  TuiLinkModule,
  TuiLoaderModule,
  TuiMaskAccessorModule,
  TuiModeModule,
  TuiMonthPipeModule,
  TuiNotificationModule,
  TuiPrimitiveCalendarModule,
  TuiPrimitiveCheckboxModule,
  TuiPrimitiveSpinButtonModule,
  TuiPrimitiveTextfieldModule,
  TuiPrimitiveYearMonthPaginationModule,
  TuiPrimitiveYearPickerModule,
  TuiRootModule,
  TuiScrollIntoViewModule,
  TuiScrollbarModule,
  TuiSvgDefsHostModule,
  TuiSvgModule,
  TuiTextfieldControllerModule,
  TuiThemeNightModule,
  TuiTooltipModule,
  TuiWrapperModule,
  TuiAccordionModule,
  TuiActionModule,
  TuiArrowModule,
  TuiAvatarModule,
  TuiBadgeModule,
  TuiBadgedContentModule,
  TuiBreadcrumbsModule,
  TuiCalendarMonthModule,
  TuiCalendarRangeModule,
  TuiCarouselModule,
  TuiCheckboxBlockModule,
  TuiCheckboxLabeledModule,
  TuiCheckboxModule,
  TuiComboBoxModule,
  TuiDataListDropdownManagerModule,
  TuiDataListWrapperModule,
  TuiElasticContainerModule,
  TuiExtractCountryCodeModule,
  TuiFieldErrorPipeModule,
  TuiFilesModule,
  TuiFilterByInputPipeModule,
  TuiFilterModule,
  TuiHighlightModule,
  TuiInputCopyModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputDateTimeModule,
  TuiInputFilesModule,
  TuiInputInlineModule,
  TuiInputModule,
  TuiInputMonthModule,
  TuiInputMonthRangeModule,
  TuiInputNumberModule,
  TuiInputPasswordModule,
  TuiInputPhoneInternationalModule,
  TuiInputPhoneModule,
  TuiInputRangeModule,
  TuiInputSliderModule,
  TuiInputTagModule,
  TuiInputTimeModule,
  TuiInputYearModule,
  TuiIslandModule,
  TuiIsoToCountryCodeModule,
  TuiItemsWithMoreModule,
  TuiLazyLoadingModule,
  TuiLineClampModule,
  TuiMarkerIconModule,
  TuiMultiSelectModule,
  TuiMultiSelectOptionModule,
  TuiPaginationModule,
  TuiPdfViewerModule,
  TuiPresentModule,
  TuiPrimitiveCalendarRangeModule,
  TuiProgressModule,
  TuiProjectClassModule,
  TuiPromptModule,
  TuiPushModule,
  TuiRadioBlockModule,
  TuiRadioGroupModule,
  TuiRadioLabeledModule,
  TuiRadioListModule,
  TuiRadioModule,
  TuiRangeModule,
  TuiRatingModule,
  TuiRoutableDialogModule,
  TuiSelectModule,
  TuiSelectOptionModule,
  TuiSliderModule,
  TuiSortCountriesPipeModule,
  TuiStepperModule,
  TuiStringifyContentPipeModule,
  TuiStringifyPipeModule,
  TuiTabsModule,
  TuiTagModule,
  TuiTilesModule,
  TuiToYearPipeModule,
  TuiToggleModule,
  TuiTreeModule,
  TuiUnfinishedValidatorModule,
  TuiValueAccessorModule,
  BrowserModule,
  AppRoutingModule,
  BrowserAnimationsModule,
  MatSidenavModule,
  MatToolbarModule,
  MatIconModule,
  MatButtonModule,
  BsDropdownModule.forRoot(),
  MatSelectModule,
  FormsModule,
  ReactiveFormsModule,
  MatMenuModule,
  MatDialogModule,
  MatTableModule,
  MatInputModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatSortModule,
  MatProgressSpinnerModule,
  MatTooltipModule,
  CdkAccordionModule,
  CdkMenuModule,
  MatRadioModule,
  MatPaginatorModule,
  DragDropModule,
  CdkTableModule,
  CdkDragdropModule,
  MatTabsModule,
  DFormsModule,
  DialogModule,
  TuiRootModule,
  TuiAlertModule,
];
