import { PolymorpheusTemplate, PolymorpheusOutlet } from "@taiga-ui/polymorpheus";
import { TuiCardLarge } from "@taiga-ui/layout";
import { WaResizeObserver } from "@ng-web-apis/resize-observer";
import { TuiFormatPhonePipe, TuiToCountryCodePipe, TuiIsoToCountryCodePipe, TuiIslandDirective, TuiWrapperModule, TuiPrimitiveTextfieldModule, TuiTextfieldControllerModule, TuiArrowComponent, TuiTooltipModule, TuiComboBoxModule, TuiInputModule, TuiInputCopyModule, TuiInputDateModule, TuiInputDateRangeModule, TuiInputDateTimeModule, TuiInputMonthModule, TuiInputMonthRangeModule, TuiInputNumberModule, TuiInputPasswordModule, TuiInputPhoneModule, TuiInputPhoneInternationalComponent, TuiInputRangeModule, TuiInputSliderModule, TuiInputTagModule, TuiInputTimeModule, TuiInputYearModule, TuiMultiSelectModule, TuiMultiSelectOptionModule, TuiSelectModule, TuiSelectOptionModule, TuiTagModule } from "@taiga-ui/legacy";
import { CdkAccordionModule } from '@angular/cdk/accordion';
import { DialogModule } from '@angular/cdk/dialog';
import { DragDropModule } from '@angular/cdk/drag-drop';
import { CdkMenuModule } from '@angular/cdk/menu';
import { ScrollingModule } from '@angular/cdk/scrolling';
import { CdkTableModule } from '@angular/cdk/table';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatDialogModule } from '@angular/material/dialog';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatMenuModule } from '@angular/material/menu';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatRadioModule } from '@angular/material/radio';
import { MatSelectModule } from '@angular/material/select';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatSortModule } from '@angular/material/sort';
import { MatTableModule } from '@angular/material/table';
import { MatTabsModule } from '@angular/material/tabs';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatTooltipModule } from '@angular/material/tooltip';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { RouterModule } from '@angular/router';
import { TuiAlertHostModule, TuiAutofilledModule, TuiCheckedModule, TuiControlModule, TuiDialogHostModule, TuiDropdownHostModule, TuiFocusVisibleModule, TuiFocusedModule, TuiHighDpiModule, TuiMediaModule, TuiPressedModule, TuiResizerModule, TuiActiveZone, TuiAutoFocus, TuiFocusTrap, TuiElement, TuiFor, TuiHovered, TuiItem, TuiPan, TuiRepeatTimes, TuiSwipe, TuiValueChanges, TuiZoom, TuiCopyProcessor, TuiFilterPipe, TuiIsPresentPipe, TuiKeysPipe, TuiMapperPipe, TuiReplacePipe, TuiDroppable, TuiValidator, TuiLet, TuiObscured } from '@taiga-ui/cdk';
// TODO: (Taiga UI migration) Use Maskito instead (this MaskAccessor is not required for it) https://maskito.dev/frameworks/angular#custom-input
import { TuiCalendarSheetPipeModule, TuiHintsHostModule, TuiMaskAccessorModule, TuiPrimitiveCalendarModule, TuiPrimitiveSpinButtonModule, TuiPrimitiveYearMonthPaginationModule, TuiPrimitiveYearPickerModule, TuiScrollIntoViewModule, TuiSvgDefsHostModule, TuiRoot, TuiAlert, TuiNotification, TuiCalendar, TuiFormatDatePipe, TuiFormatNumberPipe, TuiMonthPipe, TuiDataList, TuiError, TuiExpand, TuiLoader, TuiScrollbar, TuiGroup, TuiDropdownPortal, TuiLabel, TuiDropdown, TuiFlagPipe, TuiIcon, TuiSurface, TuiLink, TuiDialog, TuiButton, TuiHint } from '@taiga-ui/core';
import { TuiPrimitiveCalendarRangeModule, TuiProjectClassModule, TuiRadioGroupModule, TuiRadioModule, TuiRoutableDialogModule, TuiToYearPipeModule, TuiValueAccessorModule, TuiPagination, TuiDataListWrapper, TuiAccordion, TuiBreadcrumbs, TuiCalendarMonth, TuiCalendarRange, TuiCarousel, TuiPush, TuiElasticContainer, TuiFiles, TuiFilter, TuiInputInline, TuiItemsWithMore, TuiLineClamp, TuiRange, TuiSlider, TuiTiles, TuiStepper, TuiTree, TuiDataListDropdownManager, TuiHighlight, TuiImgLazyLoading, TuiUnfinishedValidator, TuiSortCountriesPipe, TuiStringifyContentPipe, TuiFilterByInputPipe, TuiFieldErrorPipe, TuiBadge, TuiCheckbox, TuiAvatar, TuiSwitch, TuiBadgedContent, TuiPresent, TuiBlock, TuiRadio, TuiTabs, TuiRating, TuiProgress, TuiRadioList, TuiStringifyPipe } from '@taiga-ui/kit';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import { AppRoutingModule } from '../app-routing.module';
import { DFormsModule } from '../core/dynamic-forms/dForms.module';
import { CdkDragdropModule } from '../Examples/cdkDrag&Drop/cdkDrag&drop.module';


export const ALL_MODULES = [
  BrowserModule,
  BrowserAnimationsModule,
  FormsModule,
  ReactiveFormsModule,
  ScrollingModule,
  PolymorpheusTemplate, PolymorpheusOutlet,
  RouterModule.forRoot([]),
  TuiActiveZone,
  TuiAlertHostModule,
  TuiAutoFocus,
  TuiAutofilledModule,
  TuiCheckedModule,
  TuiControlModule,
  TuiCopyProcessor,
  TuiDialogHostModule,
  TuiDropdownHostModule,
  TuiDroppable,
  TuiElement,
  TuiFilterPipe,
  TuiFocusTrap,
  TuiFocusVisibleModule,
  TuiFocusedModule,
  TuiFor,
  TuiHighDpiModule,
  TuiHovered,
  TuiIsPresentPipe,
  TuiItem,
  TuiKeysPipe,
  TuiLet,
  TuiMapperPipe,
  TuiMediaModule,
  TuiObscured,
  TuiPan,
  TuiDropdownPortal,
  TuiPressedModule,
  TuiRepeatTimes,
  TuiReplacePipe,
  WaResizeObserver,
  TuiResizerModule,
  TuiSwipe,
  TuiValidator,
  TuiValueChanges,
  TuiZoom,
  TuiAlert,
  TuiButton,
  TuiCalendar,
  TuiCalendarSheetPipeModule,
  TuiDataList,
  TuiDialog,
  TuiDropdown,
  TuiError,
  TuiExpand,
  TuiFlagPipe,
  TuiFormatDatePipe,
  TuiFormatNumberPipe,
  TuiFormatPhonePipe,
  TuiGroup,
  TuiHint,
  TuiHintsHostModule,
  TuiDropdown,
  TuiLabel,
  TuiLink,
  TuiLoader,
  TuiMaskAccessorModule,
  TuiMonthPipe,
  TuiNotification,
  TuiPrimitiveCalendarModule,
  TuiCheckbox,
  TuiPrimitiveSpinButtonModule,
  TuiPrimitiveTextfieldModule,
  TuiPrimitiveYearMonthPaginationModule,
  TuiPrimitiveYearPickerModule,
  TuiRoot,
  TuiScrollIntoViewModule,
  TuiScrollbar,
  TuiSvgDefsHostModule,
  TuiIcon,
  TuiTextfieldControllerModule,
  TuiTooltipModule,
  TuiWrapperModule,
  TuiAccordion,
  TuiCardLarge, TuiSurface,
  TuiArrowComponent,
  TuiAvatar,
  TuiBadge,
  TuiBadgedContent,
  TuiBreadcrumbs, TuiItem,
  TuiCalendarMonth,
  TuiCalendarRange,
  TuiCarousel,
  TuiBlock, TuiCheckbox,
  TuiLabel,
  TuiCheckbox,
  TuiComboBoxModule,
  TuiDataListDropdownManager,
  TuiDataListWrapper,
  TuiElasticContainer,
  TuiToCountryCodePipe,
  TuiFieldErrorPipe,
  TuiFiles,
  TuiFilterByInputPipe,
  TuiFilter,
  TuiHighlight,
  TuiInputCopyModule,
  TuiInputDateModule,
  TuiInputDateRangeModule,
  TuiInputDateTimeModule,
  TuiFiles,
  TuiInputInline,
  TuiInputModule,
  TuiInputMonthModule,
  TuiInputMonthRangeModule,
  TuiInputNumberModule,
  TuiInputPasswordModule,
  TuiInputPhoneInternationalComponent,
  TuiInputPhoneModule,
  TuiInputRangeModule,
  TuiInputSliderModule,
  TuiInputTagModule,
  TuiInputTimeModule,
  TuiInputYearModule,
  TuiIslandDirective,
  TuiIsoToCountryCodePipe,
  TuiItemsWithMore,
  TuiImgLazyLoading,
  TuiLineClamp,
  TuiAvatar,
  TuiMultiSelectModule,
  TuiMultiSelectOptionModule,
  TuiPagination,
  TuiPresent,
  TuiPrimitiveCalendarRangeModule,
  TuiProgress,
  TuiProjectClassModule,
  TuiPush,
  TuiBlock, TuiRadio,
  TuiRadioGroupModule,
  TuiLabel,
  TuiRadioList,
  TuiRadioModule,
  TuiRange,
  TuiRating,
  TuiRoutableDialogModule,
  TuiSelectModule,
  TuiSelectOptionModule,
  TuiSlider,
  TuiSortCountriesPipe,
  TuiStepper,
  TuiStringifyContentPipe,
  TuiStringifyPipe,
  TuiTabs,
  TuiTagModule,
  TuiTiles,
  TuiToYearPipeModule,
  TuiSwitch,
  TuiTree,
  TuiUnfinishedValidator,
  TuiValueAccessorModule,
  BrowserModule,
  AppRoutingModule,
  BrowserAnimationsModule,
  MatSidenavModule,
  MatToolbarModule,
  MatIconModule,
  MatButtonModule,
  BsDropdownModule.forRoot(),
  MatSelectModule,
  FormsModule,
  ReactiveFormsModule,
  MatMenuModule,
  MatDialogModule,
  MatTableModule,
  MatInputModule,
  MatCheckboxModule,
  MatFormFieldModule,
  MatSortModule,
  MatProgressSpinnerModule,
  MatTooltipModule,
  CdkAccordionModule,
  CdkMenuModule,
  MatRadioModule,
  MatPaginatorModule,
  DragDropModule,
  CdkTableModule,
  CdkDragdropModule,
  MatTabsModule,
  DFormsModule,
  DialogModule,
  TuiRoot,
  TuiAlert,
];
